.TH RMAPP "1" "December 27, 2024" "rmapp VERSION"
.SH NAME
rmapp \- delete leftover files of macOS applications
.SH SYNOPSIS
.B rmapp
[OPTION] [STRING]
.SH DESCRIPTION
rmapp is a simple command-line tool that helps you delete leftover files of macOS applications. Specify a keyword as an argument, find files, and select files you want to delete.
.SH OPTIONS
.TP
-h, --help
Display a short help message and exit.
.TP
-v, --version
Display version information and exit.
.TP
-c, --check
Display all matched files and exit.
.TP
-s, --silent
Silent mode
